name       : qt5-quickcontrols2
version    : 5.10.0
release    : 8
source     :
    - https://download.qt.io/official_releases/qt/5.10/5.10.0/submodules/qtquickcontrols2-everywhere-src-5.10.0.tar.xz : 818770247a3a211714dfc17f7f5a07c6cf49999ff405d36fd00fab1d5559a1a1
license    :
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls 2 Module
description: |
    Qt Quick Controls 2 provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols2.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    cd $installdir; qml_cache
