name       : qt5-quickcontrols2
version    : 5.15.10
release    : 32
source     :
    - git|https://invent.kde.org/qt/qt/qtquickcontrols2.git : 0472a07a8f39587052216d85a7ed235c531eba2c
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Quick Controls 2 Module
description: |
    Qt Quick Controls 2 provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols2.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    %qml_cache
