name       : qt5-quickcontrols2
version    : 5.12.2
release    : 13
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.2/submodules/qtquickcontrols2-everywhere-src-5.12.2.tar.xz : 1fbd703612a2c0257861e07a2b709f6fbad00cb6df70a1c2c1fafa9de522e549
license    :
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls 2 Module
description: |
    Qt Quick Controls 2 provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols2.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    %qml_cache
