name       : qt5-quickcontrols2
version    : 5.11.1
release    : 10
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtquickcontrols2-everywhere-src-5.11.1.tar.xz : bdb066fa0d51ad36a2c756d4cba63892587638e5df9b9b6ee63b963ff39ec442
license    :
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls 2 Module
description: |
    Qt Quick Controls 2 provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols2.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    %qml_cache
