name       : qt5-quickcontrols2
version    : 5.13.0
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.0/submodules/qtquickcontrols2-everywhere-src-5.13.0.tar.xz : a5cb7e6d68285203bfb1aee87551228879fa9d93d87be5c8bab38e5a79dc916d
license    :
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls 2 Module
description: |
    Qt Quick Controls 2 provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols2.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    %qml_cache
