name       : qt5-quickcontrols2
version    : 5.9.0
release    : 2
source     :
    - http://download.qt.io/official_releases/qt/5.9/5.9.0/submodules/qtquickcontrols2-opensource-src-5.9.0.tar.xz : 09ab6fc1cc5fe6ea6179cff971950cdb37b074610d0d84f0cd61052ec97c1d9c
license    :
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls 2 Module
description: |
    Qt Quick Controls 2 provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    qmake CONFIG+=release qtquickcontrols2.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
